[theme]

# One of "light" or "dark".
base = "light"

# Primary accent for interactive elements
primaryColor = '#6b5be2'

# Background color for the main content area
backgroundColor = '#f3f4ff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffffff'

# Color used for almost all text
textColor = '#1d344a'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"